# Scope and DoD

•	Consistent column names (snake_case).
•	Sensible types confirmed (and only safe coercions applied).
•	Obvious invalids handled (set to missing or clipped only when justified).
•	Missingness summarized and a policy exists per column (drop/defer/impute later).
•	Duplicates assessed (row-level and any candidate keys).
•	A cleaned artifact is saved under /processed with a versioned name.
•	Decision log is updated and shipped alongside the cleaned artifact.

Purpose: Document inspection-based decisions *before* applying transformations, so the cleaned dataset is reproducible and defensible.

# Libraries and Data Ingestion

In [2]:
# Libraries 

# Standard
import pandas as pd 
import numpy as np 

# Visualization
import matplotlib.pyplot as plt 
import seaborn as sns

# Data ingestion
from survey311.paths import PROJECT_ROOT, DATA_DIR, PROC_DIR
from survey311.project_io import (
    read_csv_from_raw,
    read_excel_from_raw,
    read_csv_from_processed,
    read_excel_from_processed,
)
from survey311.data_overview import data_overview

In [5]:
# Data Ingestion

df = read_csv_from_raw(
    "311_Resolution_Satisfaction_Survey_20260814.csv"
)

# Data Overview

In [6]:
# Data Overview

data_overview(df)

Shape: 549,244 rows × 11 columns

Columns in dataset order:

['Unique Key',
 'Agency Acronym',
 'Agency Name',
 'Complaint Type',
 'Descriptor',
 'Borough',
 'Resolution Description',
 'Survey Year',
 'Survey Month',
 'Satisfaction Response',
 'Dissatisfaction Reason']

First 3 rows:

,Unique Key,Agency Acronym,Agency Name,Complaint Type,Descriptor,Borough,Resolution Description,Survey Year,Survey Month,Satisfaction Response,Dissatisfaction Reason
0,81905052-00208441,DOHMH,Department of Health and Mental Hygiene,Smoking,Smoking Violation,BROOKLYN,This SR was administratively closed. The issue...,2024,6,Strongly Disagree,"Status updates were unhelpful, inaccurate, inc..."
1,59024125-00040603,DPR,Department of Parks and Recreation,New Tree Request,For One Address,STATEN ISLAND,NYC Parks determined that the requested locati...,2023,1,Strongly Disagree,The Agency did not correct the issue.
2,84109366-00210035,DOHMH,Department of Health and Mental Hygiene,Smoking,Smoking Violation,MANHATTAN,This SR was administratively closed. The issue...,2024,6,Strongly Disagree,Other

Last 3 rows:

,Unique Key,Agency Acronym,Agency Name,Complaint Type,Descriptor,Borough,Resolution Description,Survey Year,Survey Month,Satisfaction Response,Dissatisfaction Reason
549241,26999602-00356662,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,MANHATTAN,The Police Department responded to the complai...,2025,5,Strongly Agree,NaN
549242,28967295-00185063,HPD,Department of Housing Preservation and Develop...,Electric,Power Outage,BRONX,The Department of Housing Preservation and Dev...,2024,3,Strongly Disagree,Other
549243,86972489-00308284,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,MANHATTAN,The Police Department responded to the complai...,2025,1,Strongly Disagree,"Status updates were unhelpful, inaccurate, inc..."

Data types:

Unique Key                  str
Agency Acronym              str
Agency Name                 str
Complaint Type              str
Descriptor                  str
Borough                     str
Resolution Description      str
Survey Year               int64
Survey Month              int64
Satisfaction Response       str
Dissatisfaction Reason      str
Name: dtype, dtype: object

Numeric summary:

,count,mean,std,min,25%,50%,75%,max
Survey Year,549244.0,2024.305456,1.179242,2022.0,2023.0,2024.0,2025.0,2026.0
Survey Month,549244.0,6.267154,3.507899,1.0,3.0,6.0,10.0,12.0

Missingness — top 15 columns by missing count:

                        missing_count  missing_rate
Dissatisfaction Reason         209521      0.381472
Descriptor                      18291      0.033302
Borough                          9357      0.017036
Resolution Description           2006      0.003652
Agency Name                       101      0.000184
Unique Key                          0      0.000000
Agency Acronym                      0      0.000000
Complaint Type                      0      0.000000
Survey Year                         0      0.000000
Survey Month                        0      0.000000
Satisfaction Response               0      0.000000

Unique-value counts — top 15 columns:

Unique Key                549244
Descriptor                   819
Resolution Description       744
Complaint Type               226
Agency Name                   21
Agency Acronym                19
Survey Month                  12
Dissatisfaction Reason         9
Borough                        6
Survey Year                    5
Satisfaction Response          5
Name: n_unique, dtype: int64

Fully duplicated rows: 0

Categorical preview (top 10 levels for up to 8 columns):

• Unique Key

Unique Key
81905052-00208441    1
59024125-00040603    1
84109366-00210035    1
85454038-00096171    1
29674115-00208005    1
14798347-00257174    1
67633936-00348203    1
74223968-00208774    1
93995395-00208784    1
20627294-00212073    1
Name: count, dtype: int64

• Agency Acronym

Agency Acronym
NYPD     252579
HPD       85328
DSNY      64005
DEP       38654
DPR       28443
DOT       23670
DOF       20887
DOB       11794
DOHMH      9958
TLC        4548
Name: count, dtype: int64

• Agency Name

Agency Name
New York City Police Department                       252546
Department of Housing Preservation and Development     85300
Department of Sanitation                               63566
Department of Environmental Protection                 38646
Department of Parks and Recreation                     28426
Department of Transportation                           23664
Department of Finance                                  20873
Department of Buildings                                11789
Department of Health and Mental Hygiene                 9958
Taxi and Limousine Commission                           4548
Name: count, dtype: int64

• Complaint Type

Complaint Type
Illegal Parking            133955
Noise - Residential         34743
Blocked Driveway            30519
Heat/Hot Water              30420
Missed Collection           19577
Abandoned Vehicle           16902
Unsanitary Condition        12890
Water Maintenance           12354
Noise - Street/Sidewalk     12020
Dirty Condition             11493
Name: count, dtype: int64

• Descriptor

Descriptor
Blocked Sidewalk                 66327
Loud Music/Party                 37709
No Access                        21242
Apartment Only                   19615
Blocked Hydrant                  19449
Posted Parking Sign Violation    19100
NaN                              18291
Banging/Pounding                 16252
Trash                            15280
With License Plate               10850
Name: count, dtype: int64

• Borough

Borough
BROOKLYN         186954
QUEENS           142198
MANHATTAN        104508
BRONX             80980
STATEN ISLAND     25247
NaN                9357
Name: count, dtype: int64

• Resolution Description

Resolution Description
The Department of Housing Preservation and Development conducted or attempted to conduct an inspection.  More information about inspection results can be found through HPD's website at www.nyc.gov/hpd by using HPDONLINE (enter your address on the home page) and entering your SR number under the complaint status option.                                                                                                                                                                                                                                                                                                                                                                                                67314
The Police Department responded to the complaint and took action to fix the condition.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          56146
The Police Department responded to the complaint and determined that police action was not necessary.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           50117
The Police Department responded to the complaint and with the information available observed no evidence of the violation at that time.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         33286
The Police Department issued a summons in response to the complaint.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            24918
The Police Department responded and upon arrival those responsible for the condition were gone.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 20372
The New York City Police Department responded to the complaint and their investigation determined that no criminal violation existed. The condition was corrected without the need to issue a summons or effect an arrest. If the problem persists, please contact 311 to create another complaint. If possible, provide contact information so responding officers may reach out to you for more details. If necessary, your complaint may be referred to your local precinct's special operations units (Quality of Life, etc.). Thank you for your attention to this matter. We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.    15677
The New York City Police Department responded to the complaint and their investigation determined that police action was not necessary. If the problem persists, please contact 311 to create another complaint. If possible, provide contact information so responding officers may reach out to you for more details. We count on New Yorkers like yourself to maintain a safe City, so please let us know if you see other conditions that require our attention.                                                                                                                                                                                                                                                            15355
The Department of Sanitation investigated this complaint and found no condition at the location.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                13415
The Department of Sanitation collected the requested items.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     13216
Name: count, dtype: int64

• Satisfaction Response

Satisfaction Response
Strongly Disagree    298276
Strongly Agree       133326
Agree                 50194
Disagree              42040
Neutral               25408
Name: count, dtype: int64

{'columns': ['Unique Key',
  'Agency Acronym',
  'Agency Name',
  'Complaint Type',
  'Descriptor',
  'Borough',
  'Resolution Description',
  'Survey Year',
  'Survey Month',
  'Satisfaction Response',
  'Dissatisfaction Reason'],
 'dtypes': Unique Key                  str
 Agency Acronym              str
 Agency Name                 str
 Complaint Type              str
 Descriptor                  str
 Borough                     str
 Resolution Description      str
 Survey Year               int64
 Survey Month              int64
 Satisfaction Response       str
 Dissatisfaction Reason      str
 Name: dtype, dtype: object,
 'numeric_summary':                  count         mean       std     min     25%     50%     75%  \
 Survey Year   549244.0  2024.305456  1.179242  2022.0  2023.0  2024.0  2025.0
 Survey Month  549244.0     6.267154  3.507899     1.0     3.0     6.0    10.0

                  max
 Survey Year   2026.0
 Survey Month    12.0  ,
 'missingness':                         missing_count  missing_rate
 Dissatisfaction Reason         209521      0.381472
 Descriptor                      18291      0.033302
 Borough                          9357      0.017036
 Resolution Description           2006      0.003652
 Agency Name                       101      0.000184
 Unique Key                          0      0.000000
 Agency Acronym                      0      0.000000
 Complaint Type                      0      0.000000
 Survey Year                         0      0.000000
 Survey Month                        0      0.000000
 Satisfaction Response               0      0.000000,
 'missing_count': Dissatisfaction Reason    209521
 Descriptor                 18291
 Borough                     9357
 Resolution Description      2006
 Agency Name                  101
 Unique Key                     0
 Agency Acronym                 0
 Complaint Type                 0
 Survey Year                    0
 Survey Month                   0
 Satisfaction Response          0
 Name: missing_count, dtype: int64,
 'missing_rate': Dissatisfaction Reason    0.381472
 Descriptor                0.033302
 Borough                   0.017036
 Resolution Description    0.003652
 Agency Name               0.000184
 Unique Key                0.000000
 Agency Acronym            0.000000
 Complaint Type            0.000000
 Survey Year               0.000000
 Survey Month              0.000000
 Satisfaction Response     0.000000
 Name: missing_rate, dtype: float64,
 'n_unique': Unique Key                549244
 Descriptor                   819
 Resolution Description       744
 Complaint Type               226
 Agency Name                   21
 Agency Acronym                19
 Survey Month                  12
 Dissatisfaction Reason         9
 Borough                        6
 Survey Year                    5
 Satisfaction Response          5
 Name: n_unique, dtype: int64,
 'duplicate_rows': 0,
 'categorical_columns': ['Unique Key',
  'Agency Acronym',
  'Agency Name',
  'Complaint Type',
  'Descriptor',
  'Borough',
  'Resolution Description',
  'Satisfaction Response',
  'Dissatisfaction Reason']}